server:
  port: 7911

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: statistical-tests-project

logging:
  level:
    com.example.stats: DEBUG
